#' Generate Quarto Report for NMA Preflight Diagnostics
#'
#' Generates a comprehensive Quarto HTML report containing all preflight diagnostic outputs:
#' network sparsity, connectivity, transitivity, and covariate modifier checks.
#'
#' @param preflight An \code{nma_preflight} object generated by \code{nma_preflight()},
#'   or an \code{nma_data} network object (in which case \code{nma_preflight()} will be run first).
#' @param output_file Character; the path/filename of the output report (default: "preflight_report.html").
#' @param title Character; the title of the report (default: "NMA Preflight Diagnostics Report").
#' @param author Character; the author of the report.
#' @param browse Logical; if \code{TRUE} (default), opens the generated report in the default web browser.
#' @param ... Additional arguments passed to \code{nma_preflight()} if a network object is provided.
#'
#' @return The path to the generated report file (invisibly).
#' @export
#' @importFrom quarto quarto_render quarto_available
#' @importFrom utils browseURL
nma_preflight_report <- function(preflight, 
                                 output_file = "preflight_report.html", 
                                 title = "NMA Preflight Diagnostics Report",
                                 author = NULL,
                                 browse = TRUE,
                                 ...) {
  # Check if quarto is available
  if (!requireNamespace("quarto", quietly = TRUE)) {
    stop("The 'quarto' R package is required to generate this report. Please install it with: install.packages('quarto')")
  }
  
  if (!quarto::quarto_available()) {
    stop("Quarto CLI was not found. Please install the Quarto CLI (https://quarto.org/) or ensure it is in your system PATH.")
  }

  # If network object is provided, run nma_preflight first
  if (!inherits(preflight, "nma_preflight")) {
    cat("Input 'preflight' is not an 'nma_preflight' object. Running 'nma_preflight()' on the input first...\n")
    preflight <- nma_preflight(preflight, ...)
  }
  
  # Locate template qmd file
  template_path <- system.file("templates", "report.qmd", package = "preflightnma")
  if (template_path == "") {
    # Fallback to local dev path if package is loaded with devtools
    template_path <- file.path("inst", "templates", "report.qmd")
    if (!file.exists(template_path)) {
      stop("Could not locate the report template. Please make sure the package is installed or loaded correctly.")
    }
  }
  
  # Set up temporary directory and copy template
  temp_dir <- tempdir()
  temp_qmd <- file.path(temp_dir, "report.qmd")
  file.copy(template_path, temp_qmd, overwrite = TRUE)
  
  # Save the preflight object to a temporary rds file
  temp_rds <- file.path(temp_dir, "preflight_data.rds")
  saveRDS(preflight, file = temp_rds)
  
  # Determine parameters
  if (is.null(author)) {
    author <- Sys.info()[["user"]]
    if (is.null(author) || author == "") author <- "NMA Preflight"
  }
  
  # Render the Quarto report
  # Note: quarto_render writes output to the directory of the input file by default.
  # We render to html in the temp directory first, then copy to the output_file destination.
  cat("Rendering Quarto report... This may take a few seconds.\n")
  
  # Normalize paths for Quarto
  temp_qmd_norm <- normalizePath(temp_qmd, winslash = "/", mustWork = FALSE)
  temp_rds_norm <- normalizePath(temp_rds, winslash = "/", mustWork = FALSE)
  
  # Run render
  tryCatch({
    quarto::quarto_render(
      input = temp_qmd_norm,
      execute_params = list(
        data_path = temp_rds_norm,
        title = title,
        author = author
      ),
      quiet = TRUE
    )
  }, error = function(e) {
    stop("Failed to render the Quarto report. Error: ", e$message)
  })
  
  # Find rendered HTML
  rendered_html <- file.path(temp_dir, "report.html")
  if (!file.exists(rendered_html)) {
    stop("Rendering completed but the output HTML file could not be found.")
  }
  
  # Copy to destination
  # Ensure the output directory exists
  out_dir <- dirname(output_file)
  if (!dir.exists(out_dir) && out_dir != "") {
    dir.create(out_dir, recursive = TRUE)
  }
  
  file.copy(rendered_html, output_file, overwrite = TRUE)
  cat("Report successfully generated at: ", normalizePath(output_file), "\n")
  
  if (browse) {
    utils::browseURL(output_file)
  }
  
  return(invisible(output_file))
}
